# Generated by Django 2.1 on 2018-09-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_time', models.CharField(choices=[('standard', 'standard'), ('reduced', 'reduced')], max_length=25)),
                ('standing_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('call_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interval_start', models.TimeField()),
                ('interval_end', models.TimeField()),
            ],
        ),
    ]
