# Generated by Django 2.1 on 2018-09-03 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('call_record_end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_record_end', to='api.CallRecord')),
                ('call_record_start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_record_start', to='api.CallRecord')),
            ],
        ),
    ]
